### ISSUE TITLE
[0.1.6] No more IE

### ISSUE THREAD

**Issue by devel-pa** [filamentgroup/a-font-garde#11]
Looks like the small update between 0.1.5 and 0.1.6 makes it useless for IE9+.
The patch was welcome as the scroll bar was going way to the right.

**Comment by zachleat** [comment]
I cannot confirm this report. Here is a screenshot of 0.1.6 in IE9/Windows 7:
![image](https://cloud.githubusercontent.com/assets/39355/6787794/1057c56c-d163-11e4-9818-02c39e6168ab.png)

Icons are showing correctly.

**Comment by devel-pa** [comment]
Hi, I've made tests with your demo and I can confirm that it's working.
It is happening only on my application 0.1.5 works, but big horizontal scroll, 0.1.6 doesn't work.
I have no explanation, yet.

**Comment by devel-pa** [comment]
Looks specific to my font. As long as I'm making the size of the sample from 48px to 61px (not less) it's starts working. I have no idea why.

**Comment by devel-pa** [comment]
It was the font that didn't worked with 0.1.6.
Thanks, and sry for the issue.

**Comment by devel-pa** [comment]
I found the issue between this library and a font in IE: when generating a font and set the font height for the font, it fails.

**Comment by devel-pa** [comment]
Looks like the only way to solve my issue is to increase the font-size inside your library to 61px.
