### ISSUE TITLE
Add aria-hidden="true" on TEST_STRING 

### ISSUE THREAD

**Issue by audreymaniez** [filamentgroup/a-font-garde#12]
Hello, 
thanks for the script ! :-)

The TEST_STRING generated by the script at the end of html is read by a screen reader, but that's not content.

Adding `aria-hidden="true"` on the `div` would solve that issue. Screen reader won't read it anymore.

afontgarde.js line 37
`html = '<div aria-hidden="true" style="' + style + '">' + TEST_STRING + '</div>';`

That's good for web accessibility :-)
Thank you !

**Comment by zachleat** [comment]
Yes! You’re absolutely right!

**Comment by zachleat** [comment]
Actually, this technically belongs in an upstream dependency: https://github.com/zachleat/fontfaceonload but don’t worry about it.
